import Link from "next/link";
import { SiteHeader } from "@/components/shared/site-header";

export default function FeasibilityPage() {
  return <><SiteHeader inApp /><main className="wrap proof-main"><div className="proof-stamps"><span>FEASIBILITY RECORD</span><span>READ-ONLY</span><span>NO FUNDS MOVED</span></div><h1>Evidence for the first<br />NVIDIA → Venus route.</h1><p className="proof-lead">Collected 2026-09-29 through live Binance Web3 API reads and executable quote requests. These observations are historical quote-time evidence, not a completed transaction or a guarantee of today’s quote.</p>
    <div className="proof-summary"><div><small>SOURCE</small><strong>NVDAon · Ondo</strong></div><span>→</span><div><small>SETTLEMENT</small><strong>USDT</strong></div><span>→</span><div><small>TARGET</small><strong>NVDAB · bStocks</strong></div><span>→</span><div><small>DESTINATION</small><strong>Venus</strong></div></div>
    <section className="proof-section"><div className="eyebrow">01 / ISSUER CONSTRAINT</div><h2>The direct pair was refused.</h2><p>Direct NVDAon → NVDAB quotes at approximately $10, $100 and $500 returned HTTP 200 with Binance business code <code>40368</code>: Ondo assets on BSC may only pair with allowed stablecoins. The application compiles the USDT route directly.</p></section>
    <section className="proof-section"><div className="eyebrow">02 / QUOTE-TIME EXPOSURE</div><h2>Two valid legs, normalized.</h2><div className="proof-table"><div><span>Approximate source size</span><span>Exposure retained</span><span>Exposure reduction</span></div><div><strong>~$10</strong><strong>99.9583%</strong><strong>0.0417%</strong></div><div><strong>~$100</strong><strong>99.9264%</strong><strong>0.0736%</strong></div><div><strong>~$500</strong><strong>99.9156%</strong><strong>0.0844%</strong></div></div><p>NVDAon and NVDAB have different token-to-share ratios. These figures compare NVIDIA-equivalent shares, not raw token counts or dollar values.</p></section>
    <section className="proof-section"><div className="eyebrow">03 / VENUS DESTINATION</div><h2>The compatible market was investable.</h2><p>Binance DeFi Data returned a Venus NVDAB investment with <code>investable=true</code> at collection time. EquityRelay discovers and checks the investment again for every live preview.</p><p className="proof-code">Recorded investment ID: <code>1c520367b6779442806f2efe6da12afd27c747e49b0d3296ac8bdb7e87104eb8</code></p></section>
    <section className="proof-section"><div className="eyebrow">04 / AUTHORIZATION PREFLIGHT · READ-ONLY · NO FUNDS MOVED</div><h2>A broad approval was rejected.</h2><p>In a live 2026-09-29 preflight for 0.05 NVDAon, Binance Trading returned exact-amount approvals for both indicative swap legs when EquityRelay set <code>approveAmount</code> to each leg’s source amount. The DeFi deposit builder requested unlimited NVDAB access. EquityRelay rejected that approval and locally constructed an unsigned replacement for exactly 0.050001119388168954 NVDAB, the indicative deposit amount in that run. The Binance deposit calldata was left unchanged.</p><p>Separate read-only simulations of the three unsigned approvals passed. Swap and deposit simulations remained blocked by that wallet’s allowance or balance state; the approval simulations did not change it. The quote and replacement amount can change. No approval was signed, no transaction was sent, and this is not execution proof.</p></section>
    <div className="proof-end"><div><strong>What this record proves</strong><p>A quote-time route existed on the observed date. It does not prove that a swap settled, a Venus deposit occurred, or a position was independently verified.</p></div><Link href="/app" className="primary-button">Build a live preview <span>↗</span></Link></div>
  </main></>;
}
