import Link from "next/link";
import { SiteHeader } from "@/components/shared/site-header";

const steps = [
  ["01", "Choose a destination", "Tell us where you want your NVIDIA to work. Venus is the first supported destination."],
  ["02", "Compile the right rail", "We resolve issuer rules, live stock ratios and the two allowed conversion legs."],
  ["03", "Check your limit", "Projected NVIDIA-equivalent exposure is compared with the reduction you allow."],
  ["04", "See the decision", "A read-only preview returns PASS, BLOCKED or UNAVAILABLE with the evidence behind it."],
];

export default function Home() {
  return <><SiteHeader /><main>
    <section className="hero wrap">
      <div className="hero-copy"><div className="eyebrow">TOKENIZED STOCK ROUTING · BNB CHAIN</div><h1>Own the stock.<br /><em>We handle the rail.</em></h1><p>Use the tokenized stock you already hold in the BNB app you actually want. EquityRelay finds the compatible representation and checks every route against your exposure limit.</p><div className="hero-actions"><Link className="primary-button" href="/app">Route my stock <span aria-hidden="true">↗</span></Link><Link className="secondary-button" href="/proof/feasibility">See feasibility evidence <span aria-hidden="true">↗</span></Link></div><div className="hero-caption"><span className="live-dot" /> LIVE DATA WHEN AVAILABLE <b>·</b> READ-ONLY PHASE 1</div></div>
      <div className="hero-art" aria-label="NVIDIA to Venus route illustration"><div className="art-kicker">DESTINATION / VENUS</div><div className="art-heading">Your NVIDIA<br /><span>has somewhere to go.</span></div><div className="art-route"><div><span className="art-node">N</span><b>Current</b><small>Ondo representation</small></div><span className="art-connector">↗</span><div><span className="art-node alt">N</span><b>Compatible</b><small>bStocks representation</small></div><span className="art-connector">↗</span><div><span className="art-node venus">V</span><b>Destination</b><small>Venus</small></div></div><div className="art-footer"><span>ONE UNDERLYING STOCK</span><strong>ONE CLEAR LIMIT</strong></div></div>
    </section>
    <section className="section problem" id="why"><div className="wrap problem-grid"><div><div className="eyebrow">THE PROBLEM</div><h2>Same stock.<br /><em>Different rails.</em></h2></div><div><p>NVIDIA can exist on BNB Chain through different issuers. A destination may accept one representation while you already hold another.</p><p>Venus accepts the bStocks NVIDIA asset. If you hold the Ondo representation, the valid route uses USDT as a settlement step. You should not have to discover that plumbing yourself.</p><div className="flow-strip"><span>NVIDIA stock</span><i>→</i><span>compatible representation</span><i>→</i><span>Venus</span></div></div></div></section>
    <section className="section how wrap" id="how"><div className="section-header"><div><div className="eyebrow">HOW IT WORKS</div><h2>A destination first.<br />A route that makes sense.</h2></div><p>No token selector to decipher. Start with the stock and what you want it to do.</p></div><div className="step-grid">{steps.map(([number, title, body]) => <article key={number} className="step-card"><span>{number}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className="section safety" id="safety"><div className="wrap safety-grid"><div><div className="eyebrow">BUILT-IN REFUSAL</div><h2>Unsafe is<br /><em>a valid answer.</em></h2><p>You choose the maximum loss of NVIDIA-equivalent exposure. EquityRelay compares the live quoted route with that limit before presenting a decision.</p><Link href="/app" className="text-link">Test your own limit <span>↗</span></Link></div><div className="safety-cards"><div className="safety-card pass"><div><span className="mini-state">PASS</span><span>ILLUSTRATIVE POLICY EXAMPLE</span></div><strong>99.93%</strong><small>projected retention · 99.50% minimum</small><p>Inside the user’s limit. Still only a read-only quote preview in Phase 1.</p></div><div className="safety-card block"><div><span className="mini-state">BLOCKED</span><span>ILLUSTRATIVE POLICY EXAMPLE</span></div><strong>98.71%</strong><small>projected retention · 99.50% minimum</small><p>Outside the limit. No transaction is prepared or submitted.</p></div></div></div></section>
    <section className="section evidence-section wrap" id="evidence"><div className="section-header"><div><div className="eyebrow">RESEARCH EVIDENCE · 2026-09-29</div><h2>A route tested<br />against live APIs.</h2></div><p>Our feasibility run used live Binance Web3 reads and quotes. It did not move funds. The product UI now repeats those checks for your amount and address.</p></div><div className="evidence-band"><div><span>01 / ISSUER RULE</span><strong>Direct pair rejected</strong><p>Binance business code 40368 required an allowed stablecoin settlement step.</p></div><div><span>02 / VALID ROUTE</span><strong>Two legs quoted</strong><p>NVDAon → USDT → NVDAB succeeded at three tested sizes.</p></div><div><span>03 / DESTINATION</span><strong>Venus found</strong><p>The Binance DeFi catalogue returned an investable NVDAB Venus investment.</p></div></div><Link href="/proof/feasibility" className="secondary-button evidence-link">See feasibility evidence <span>↗</span></Link></section>
    <section className="section built-section"><div className="wrap built-grid"><div><div className="eyebrow">BUILT FOR BNB</div><h2>Each integration<br />has a job.</h2><p>Binance RWA Data identifies the stock representations and their share ratios. Trading supplies the two quotes. DeFi Data checks whether Venus accepts the destination asset.</p></div><div className="integration-list"><div><span>01</span><strong>Binance RWA Data</strong><small>Identify + normalize</small></div><div><span>02</span><strong>Binance Trading</strong><small>Quote the allowed route</small></div><div><span>03</span><strong>Binance DeFi Data</strong><small>Verify destination availability</small></div><div><span>04</span><strong>BNB Chain</strong><small>Canonical asset network</small></div></div></div></section>
    <section className="closing wrap"><div className="eyebrow">EQUITYRELAY / START HERE</div><h2>Your stock.<br />Your destination.<br /><em>Your limit.</em></h2><Link href="/app" className="primary-button">Route my stock <span>↗</span></Link></section>
  </main><footer className="footer wrap"><div className="brand"><span className="brand-mark">E<span>↗</span></span> EquityRelay</div><div><Link href="/proof/feasibility">Feasibility record</Link><a href="https://www.bnbchain.org/" target="_blank" rel="noreferrer">BNB Chain ↗</a></div><small>Read-only route previews. Informational only; not investment advice.</small></footer></>;
}
