"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import type { PreflightAction, PreflightResult, PreflightStage, RoutePreflight } from "@/types/preflight";

function shortNumber(value: string | null): string {
  if (value === null) return "—";
  const [whole, fraction] = value.split(".");
  return fraction ? `${whole}.${fraction.slice(0, 8).replace(/0+$/, "") || "0"}` : whole;
}

function actionTitle(action: PreflightAction): string {
  if (action.kind === "APPROVAL") return action.authorization?.source === "EQUITYRELAY_BOUNDED_REPLACEMENT" ? `Approve exact ${action.tokenInLabel} amount` : `Approve ${action.tokenInLabel}`;
  if (action.kind === "RFQ") return `Review ${action.tokenInLabel} RFQ signing request`;
  if (action.kind === "DEPOSIT") return `Supply ${action.tokenInLabel} to Venus`;
  return `${action.tokenInLabel} → ${action.tokenOutLabel ?? "destination"}`;
}

function ActionRow({ action }: { action: PreflightAction }) {
  return <div className={`preflight-action ${action.approvalExceedsInput ? "wide-approval" : ""}`}>
    <div className="preflight-action-head"><span className="action-kind">{action.kind}</span><strong>{actionTitle(action)}</strong></div>
    {action.kind === "APPROVAL" ? <p>{action.authorization?.source === "EQUITYRELAY_BOUNDED_REPLACEMENT" ? "Approval generated by EquityRelay safety guard. " : "Binance approval, checked against the exact route amount. "}Requested allowance: {action.authorization?.requestedAmountHuman ?? "See raw units in transaction details"} {action.tokenInLabel}.</p>
      : action.kind === "RFQ" ? <p>This is an EIP-712 signing path. There is no EVM swap transaction to simulate or submit here.</p>
      : <p>{action.kind === "DEPOSIT" ? "Deposit calldata generated by Binance DeFi API. " : ""}{action.amountInHuman ? `${shortNumber(action.amountInHuman)} ${action.tokenInLabel}` : `${action.amountInRaw} raw ${action.tokenInLabel} units`}{action.kind === "SWAP" && action.minAmountOutRaw ? ` · Minimum receive: ${action.minAmountOutHuman ? `${shortNumber(action.minAmountOutHuman)} ${action.tokenOutLabel}` : `${action.minAmountOutRaw} raw ${action.tokenOutLabel} units`}` : ""}</p>}
    {action.kind === "APPROVAL" && <p className="approval-simulation">Approval simulation: {action.simulation.status.replaceAll("_", " ")}{action.simulation.failReason ? ` · ${action.simulation.failReason}` : ""}</p>}
    <details className="transaction-details"><summary>Inspect transaction details</summary><dl>
      <div><dt>{action.authorization?.source === "EQUITYRELAY_BOUNDED_REPLACEMENT" ? "Locally constructed token target" : "Target returned by Binance"}</dt><dd>{action.to ?? "RFQ typed data; no EVM target"}</dd></div>
      <div><dt>Sender</dt><dd>{action.from}</dd></div>
      <div><dt>Calldata / signing summary</dt><dd>{action.calldataSummary}</dd></div>
      {action.rawCalldata && <div className="full-detail"><dt>Exact unsigned calldata</dt><dd>{action.rawCalldata}</dd></div>}
      <div><dt>Native BNB value</dt><dd>{action.valueWei === null ? "Not an EVM transaction" : `${action.valueWei} wei`}</dd></div>
      {action.approvalSpender && <div><dt>Approval spender</dt><dd>{action.approvalSpender}</dd></div>}
      {action.approvalAmountRaw && <div><dt>Exact approval amount · raw units</dt><dd>{action.approvalAmountRaw}</dd></div>}
      {action.authorization && <div><dt>Approval source and scope</dt><dd>{action.authorization.source} · {action.authorization.scope}</dd></div>}
      {action.minAmountOutRaw && <div><dt>Minimum receive · raw units</dt><dd>{action.minAmountOutRaw}</dd></div>}
      {action.slippagePercent && <div><dt>Binance returned slippage</dt><dd>{action.slippagePercent}%</dd></div>}
      {action.gasLimit && <div><dt>Gas limit</dt><dd>{action.gasLimit}</dd></div>}
      {action.gasPrice && <div><dt>Gas price</dt><dd>{action.gasPrice}</dd></div>}
      {action.maxFeePerGas && <div><dt>Max fee per gas</dt><dd>{action.maxFeePerGas}</dd></div>}
      {action.maxPriorityFeePerGas && <div><dt>Priority fee per gas</dt><dd>{action.maxPriorityFeePerGas}</dd></div>}
    </dl></details>
  </div>;
}

function Stage({ number, stage }: { number: string; stage: PreflightStage }) {
  const simulation = stage.actions.find(action => action.kind === "SWAP" || action.kind === "RFQ" || action.kind === "DEPOSIT")?.simulation;
  return <article className="preflight-stage"><div className="preflight-stage-head"><span className="stage-number">{number}</span><div><h3>{stage.label}</h3>{stage.indicative && <small>INDICATIVE · MUST BE REFRESHED LATER</small>}</div><strong className={`build-tag ${stage.buildStatus.toLowerCase()}`}>BUILD {stage.buildStatus}</strong></div>
    <div className="stage-state-line"><span>AUTHORIZATION <strong>{stage.authorizationStatus.replaceAll("_", " ")}</strong></span><span>BINANCE SIMULATION <strong className={`simulation-status ${stage.simulationStatus.toLowerCase()}`}>{stage.simulationStatus.replaceAll("_", " ")}</strong></span></div>
    {stage.simulationPrerequisite === "REQUIRES_PRIOR_APPROVAL_STATE" && <p className="stage-prerequisite">The swap simulation needs an allowance that this read-only plan has not created. Its failure does not establish that the swap is invalid.</p>}
    {stage.simulationPrerequisite === "INDICATIVE_AFTER_LEG1" && <p className="stage-prerequisite">Indicative only. The amount and authorization must be rebuilt after the preceding swap settles.</p>}
    {stage.rejectedAuthorization && <div className="approval-rejection"><strong>Binance approval rejected</strong><p>{BigInt(stage.rejectedAuthorization.requestedAmountRaw) === 2n ** 256n - 1n ? "Unlimited" : stage.rejectedAuthorization.requestedAmountHuman ?? "Broad"} {stage.actions[0]?.tokenInLabel ?? "token"} access was requested for a fixed deposit. EquityRelay replaced it with an unsigned exact-amount approval for {stage.rejectedAuthorization.allowedAmountHuman ?? "the exact raw deposit amount"} {stage.actions[0]?.tokenInLabel ?? "tokens"}.</p></div>}
    {stage.reason && <p className="stage-reason">{stage.reason}</p>}
    {stage.actions.length ? <div className="preflight-actions">{stage.actions.map((action, index) => <ActionRow key={`${action.kind}-${index}`} action={action} />)}</div> : <p className="stage-no-actions">No validated unsigned action is available for this stage.</p>}
    {simulation && (simulation.balanceChanges.length > 0 || simulation.allowanceChanges.length > 0) && <details className="simulation-evidence"><summary>Inspect simulation changes returned by Binance</summary>
      {simulation.balanceChanges.map((change, index) => <p key={`balance-${index}`}>Balance · {change.tokenAddress} · {change.change}</p>)}
      {simulation.allowanceChanges.map((change, index) => <p key={`allowance-${index}`}>Allowance · {change.tokenAddress} · {change.before} → {change.after}</p>)}
    </details>}
    {stage.previewDetails && <div className="stage-preview-details">
      {stage.previewDetails.estimatedNetworkFee && <span>Estimated network fee: {stage.previewDetails.estimatedNetworkFee}</span>}
      {stage.previewDetails.healthFactorBefore && <span>Health factor: {stage.previewDetails.healthFactorBefore} → {stage.previewDetails.healthFactorAfter ?? "unavailable"}</span>}
      {stage.previewDetails.balanceChanges.map((x, i) => <span key={i}>{x.tokenSymbol} balance change: {x.amount}{x.valueUsd ? ` · ${x.valueUsd} USD` : ""}</span>)}
      {stage.actions[0]?.simulation.warnings.map((warning, i) => <span key={`warning-${i}`}>Warning: {warning}</span>)}
    </div>}
  </article>;
}

function FullReview({ data }: { data: RoutePreflight }) {
  const [wallet, setWallet] = useState<string | null>(null);
  const [savedRoute, setSavedRoute] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState("");
  const [firstStep, setFirstStep] = useState<{ actionKind: string; amountHuman: string | null; tokenLabel: string;
    minimumReceiveHuman: string | null; actionHash: string; simulationStatus: string } | null>(null);
  useEffect(() => {
    const refresh = () => { void fetch("/api/auth/session", { cache: "no-store" }).then(async response => {
      const session = await response.json() as { wallet?: string | null };
      setWallet(response.ok ? session.wallet ?? null : null);
    }).catch(() => setWallet(null)); };
    refresh();
    window.addEventListener("equityrelay-auth-changed", refresh);
    return () => window.removeEventListener("equityrelay-auth-changed", refresh);
  }, []);
  const quoteWallet = data.leg1.actions[0]?.from;
  const walletMatches = !!wallet && !!quoteWallet && wallet.toLowerCase() === quoteWallet.toLowerCase();
  async function saveReview() {
    if (!walletMatches || savedRoute) return;
    setSaving(true); setSaveError("");
    try {
      const response = await fetch("/api/execution/routes", { method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ underlying: "NVDA", sourceRepresentation: "ondo", amount: data.routePreview.amount,
          destination: "venus", maxExposureLossBps: data.routePreview.maxExposureLossBps }) });
      if (!response.ok) throw new Error("Authenticated review could not be saved. Live route policy or storage may be unavailable.");
      const body = await response.json() as { routeId: string };
      setSavedRoute(body.routeId);
    } catch (error) { setSaveError(error instanceof Error ? error.message : "Review unavailable."); }
    finally { setSaving(false); }
  }
  async function prepareFirstStep() {
    if (!savedRoute || firstStep) return;
    setSaving(true); setSaveError("");
    try {
      const response = await fetch(`/api/execution/routes/${savedRoute}/review`, { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" });
      if (!response.ok) throw new Error("A fresh read-only action could not be built. The route may need another review.");
      setFirstStep(await response.json() as NonNullable<typeof firstStep>);
    } catch (error) { setSaveError(error instanceof Error ? error.message : "Review unavailable."); }
    finally { setSaving(false); }
  }
  const approvals = [data.leg1, data.leg2Indicative, data.venusDepositIndicative].flatMap(stage => stage.actions).filter(action => action.kind === "APPROVAL");
  return <section className="preflight-review" id="preflight-review" aria-live="polite"><div className="preflight-review-head"><div><div className="eyebrow">READ-ONLY PREFLIGHT · BNB CHAIN</div><h2>NVIDIA → Venus</h2><p>Binance-built transaction actions and EquityRelay’s bounded approval replacement. Nothing has been signed or submitted.</p></div><span className={`overall-tag ${data.overallPreflightState.toLowerCase()}`}>{data.overallPreflightState.replaceAll("_", " ")}</span></div>
    <div className="preflight-summary authorization-summary"><div><small>ROUTE POLICY</small><strong className="good">{data.routePolicy}</strong></div><div><small>TRANSACTION BUILD</small><strong>{[data.leg1, data.leg2Indicative, data.venusDepositIndicative].every(stage => stage.buildStatus === "READY") ? "READY" : "UNAVAILABLE"}</strong></div><div><small>AUTHORIZATION SAFETY</small><strong>{data.authorizationSafety.replaceAll("_", " ")}</strong></div><div><small>SIMULATION</small><strong>{data.overallPreflightState === "WALLET_STATE_BLOCKED" ? "WALLET STATE BLOCKED" : data.overallPreflightState.replaceAll("_", " ")}</strong></div><div><small>EXECUTION READINESS</small><strong>{data.executionReadiness.replaceAll("_", " ")}</strong></div></div>
    <p className="approval-count">{approvals.length} unsigned approvals in the reviewed plan · Projected exposure retained: {shortNumber(data.routePreview.retentionPercent)}%</p>
    <Stage number="01" stage={data.leg1} /><Stage number="02" stage={data.leg2Indicative} /><Stage number="03" stage={data.venusDepositIndicative} />
    <div className="safety-summary"><div className="eyebrow">SAFETY SUMMARY</div><h3>What the evidence says</h3><p>EquityRelay never asks for unlimited token access when the route only requires a fixed amount.</p><ul>{data.safetyWarnings.map((warning, index) => <li key={index}>{warning}</li>)}</ul><p>Future execution requires three separate confirmations: leave Ondo, convert the actual settled USDT, and supply the actual received NVDAB to Venus. This review is read-only.</p></div>
    <div className="execution-review-save"><div><span className="eyebrow">AUTHENTICATED EXECUTION REVIEW</span><p>{savedRoute ? "Review saved with your authenticated wallet. No transaction was prepared for signing." : walletMatches ? "Your signed-in wallet matches the quote address. Save a fresh policy-passing route record for later review." : wallet ? "The signed-in wallet differs from the quote address. Rebuild the quote for your signed-in wallet." : "Connect and authenticate the quote wallet above to save this review."}</p></div>
      {savedRoute ? <><Link href={`/proof/route/${savedRoute}`}>View route status ↗</Link><button type="button" onClick={() => void prepareFirstStep()} disabled={saving || !!firstStep}>{firstStep ? "First action reviewed" : saving ? "Building…" : "Build read-only first action"}</button></> : <button type="button" onClick={() => void saveReview()} disabled={!walletMatches || saving}>{saving ? "Refreshing route…" : "Save read-only review"}</button>}
      {firstStep && <div className="saved-action-summary"><span className="handoff-state">READY FOR WALLET REVIEW</span><p>First action: {firstStep.actionKind === "APPROVAL" ? "bounded approval" : "swap"} · {firstStep.amountHuman ?? "Exact raw amount"} {firstStep.tokenLabel} · Binance simulation {firstStep.simulationStatus.replaceAll("_", " ")}.</p><strong>MAINNET EXECUTION STILL LOCKED</strong><p>The final wallet handoff will refresh expired quotes before exposing transaction fields. No transaction request is enabled in this build.</p><details><summary>Inspect action identity</summary><code>{firstStep.actionHash}</code></details></div>}
      {saveError && <small role="alert">{saveError}</small>}</div>
    <div className="execution-steps"><div className="eyebrow">FUTURE CONFIRMATIONS</div><div><strong>01 · Leave Ondo</strong><span>Review bounded source approval and minimum USDT receive</span><button type="button" disabled>Review · mainnet execution not armed</button></div><div><strong>02 · Change representation</strong><span>Locked until leg 1 confirms and actual USDT is measured</span></div><div><strong>03 · Supply to Venus</strong><span>Locked until leg 2 confirms and actual NVDAB is measured</span></div></div>
    <div className="preflight-finish">READ-ONLY PREFLIGHT <span>·</span> NOTHING HAS BEEN SIGNED OR SUBMITTED <span>·</span> MAINNET EXECUTION NOT ARMED</div>
  </section>;
}

export function PreflightReview({ result }: { result: PreflightResult }) {
  if (result.kind === "preflight") return <FullReview data={result} />;
  return <section className="preflight-review refusal" id="preflight-review" role="status"><div className="eyebrow">READ-ONLY PREFLIGHT</div><h2>Preflight stopped</h2><p>The live route was rechecked and is now {result.routePolicy}. No transaction was submitted.</p><strong>{result.reason}</strong></section>;
}
